# state.py

from typing import Dict, Any, TypedDict, List, Optional
from langchain_core.messages import AnyMessage


class State(TypedDict, total=False):
    """
    Global NL2SQL State used across the entire pipeline.

    This state structure is designed for:
      - schema_linker
      - sql_synthesis
      - sql_validator
      - sql_executor
      - debug_agent (retry attempts)
      - answering_agent
      - conversation memory

    Fields:
    --------
    messages:
        Full chat conversation as LangChain AnyMessage objects
    question:
        Original user question
    query_type:
        "general" or "data"
    schema_links:
        Dict returned by schema_linker { "tables": [...], "columns": {...} }
    sql:
        SQL generated by sql_synthesis
    validated_sql:
        SQL after validation
    execution_error:
        Error from executor or validator (if any)
    rows:
        Result rows (list of dicts)
    row_count:
        Number of returned rows
    retries:
        Number of times debug_agent was invoked
    result:
        Final natural-language answer from answering_agent
    extra_field:
        Reserved for future use
    sql_query:
        Alias for sql (some tools may expect this name)
    """

    messages: List[AnyMessage]
    question: str
    query_type: str
    schema_links: Dict[str, Any]
    sql: str
    validated_sql: str
    execution_error: str
    rows: List[Dict[str, Any]]
    row_count: int
    retries: int
    debug_triggered_times: int
    result: str
    extra_field: Any
    sql_query: str  # alias for SQL


# Optional: a runtime class wrapper if you want mutable state
class GlobalAgentState:
    def __init__(self):
        self.retries = 0  # matches 'retries' field
        self.debug_triggered_times = 0
        self.messages: List[AnyMessage] = []  # chat history
        self.state: State = {}  # actual TypedDict state container

    def reset(self):
        """Resets retry count and clears state except messages."""
        self.retries = 0
        self.debug_triggered_times = 0
        self.state = {}


# Single shared instance
GLOBAL_STATE = GlobalAgentState()
STATE = GLOBAL_STATE
